<html>
<style>
/* Add a black background color to the top navigation */
.topnav {
    background-color: #333;
    overflow: hidden;
}

/* Style the links inside the navigation bar */
.topnav a {
  float: left;
  color: #f2f2f2;
  text-align: center;
  padding: 14px 16px;
  text-decoration: none;
  font-size: 17px;
}

/* Change the color of links on hover */
.topnav a:hover {
  background-color: #ddd;
  color: black;
}

/* Add a color to the active/current link */
.topnav a.active {
  background-color: #4CAF50;
  color: white;
}

/* Right-aligned section inside the top navigation */
.topnav-right {
  float: right;
}
</style>
<body>

<div class="topnav">
  <a href="task1.php">Task1</a>
  <a href="task2.php">Task2</a>
  <a href="task3.php">Task3</a>
  <a href="task4.php">Task4</a>
  <a href="task5.php">Task5</a>
  <a href="task6.php">Task6</a>
  <a href="task7.php">Task7</a>
  <a href="task8.php">Task8</a>
  <a href="task9.php">Task9</a>


  </div>

</body>
</html>